# Generated by Django 4.1.5 on 2023-02-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('score', models.DecimalField(decimal_places=4, max_digits=12)),
            ],
        ),
    ]
